# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd6bfb861c77f92629567f141d8dfa6d76366c3821a56c63183e9c3a60bc58d866701d9e447ebb8dc39fb6ab93a5a571073a8bce421b8060dacd6b565b086462

test:
  secret_key_base: 7e9c8cbbcdfa1f9d12401ccba202e82a5b52904329c2b58747a4566d912d26629b7685ffd2933a12b44a1a102ad6988bee31439bc8ab205c89172222122242f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
